apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    ngnix.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: post.com
      http:
        paths:
          - path: /posts/create
            pathType: Prefix
            backend:
              service:
                name: posts-clutserip-srv
                port:
                  number: 4000
          - path: /posts
            backend: 
                service:
                  name: query-srv
                  servicePort: 4002
          - path: /posts?(.*)/comments
            backend: 
                service:
                  name: comments-srv
                  servicePort: 4001
          - path: /
            backend: 
                service:
                  name: client-srv
                  servicePort: 3000                 

